# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f37f809f5885d3f01ebe847f439bda742a67584908879f428768bd4ef1ad8b153ef1dad5ec6df2048ec6c6f7167010d07b5d25893a0f8687e9512c01f3896b78

test:
  secret_key_base: 7e5fcc384114bb002de6b01c8beeda45f3ceb4818a4952bff0a4d769710f68695ea73f90867b1104812ed1fc57e7f08b8e366c0e342ea88376092f61f68b8766

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
